# this manifest is for the F-Droid repository
AntiFeatures:
  NonFreeNet:
    en-US: Optional VirusTotal API integration for app scanning.
Categories:
  - System
  - Security
License: MIT
SourceCode: https://github.com/nikescar/uad-shizuku
IssueTracker: https://github.com/nikescar/uad-shizuku/issues

AutoName: uad-shizuku

RepoType: git
Repo: https://github.com/nikescar/uad-shizuku.git

Builds:
  - versionName: 0.0.6
    versionCode: 239015706
    commit: v0.0.6
    # init: echo 'started init.'
    output: mobile/app/build/outputs/apk/release/app-release.apk
    # prebuild: echo 'started prebuild'
    scanignore:
      - mobile/Cargo.toml
      - Cargo.toml
    build:
      - source $HOME/.cargo/env
      - cd mobile
      - cargo ndk -t armeabi-v7a -o app/src/main/jniLibs/ build --release --lib
      - cargo ndk -t arm64-v8a -o app/src/main/jniLibs/ build --release --lib
      - cargo ndk -t x86 -o app/src/main/jniLibs/ build --release --lib
      - cargo ndk -t x86_64 -o app/src/main/jniLibs/ build --release --lib
      - gradle assembleRelease
    # postbuild: echo 'postbuild.'
    # antifeatures:
    #  - NonFreeAssets
    #  - NonFreeNet

AutoUpdateMode: Version v%v
UpdateCheckMode: HTTP
UpdateCheckData: https://api.github.com/repos/nikescar/uad-shizuku/releases/latest|"id":\s*(\d+)|.|"tag_name":\s*"v([^"]+)"
CurrentVersion: 0.0.6
CurrentVersionCode: 239015706